Repository grafana/levitate, pull requests merged in 2022-08, with the labels that each got.

#108 Add is-compatible command
  README.md
  src/bin.ts
  src/command.is-compatible.ts
  src/index.ts
  src/tests/command.is-compatible.test.ts
  src/tests/test-utils.ts
  src/tests/utils.npm.test.ts
  src/tests/utils.typescript.test.ts
  src/types.ts
  src/utils.compare.source.ts
  src/utils.compiler.imports.ts
  src/utils.npm.ts
  src/utils.print.comparison.ts
  src/utils.typescript.ts
  tsconfig.json
Labels: enhancement

#114 Bump version to 0.4.0
  CHANGELOG.md
  package.json
Labels: release

#118 Better CLI report and exit code for is-compatible
  CHANGELOG.md
  package.json
  src/bin.ts
  src/command.is-compatible.ts
  yarn.lock
Labels: enhancement

#131 Fix: not reading export files from files containing dots on their names
  README.md
  package.json
  src/tests/utils.compiler.exports.test.ts
  src/utils.compiler.exports.ts
  src/utils.npm.ts
  yarn.lock
Labels: bug

#137 Detect function parameter types changes
  CHANGELOG.md
  fixtures/compare/bundle-new-props.tsx
  fixtures/compare/bundle-old-props.tsx
  jest.config.js
  package.json
  src/tests/utils.compare.test.ts
  src/types.ts
  src/utils.compare.ts
  src/utils.diff.ts
  src/utils.print.comparison.ts
  src/utils.typescript.ts
  yarn.lock
Labels: enhancement

#37 CI: Refactor Github workflows
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/create-release.yml
  .github/workflows/npm-bump-version.yml
  .github/workflows/publish-npm.yml
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement, github_actions
